version: '3.7'
services:
  api:
    image: api-web-service-1:dev
    build: 
      context: "./Service 1"
    container_name: api-web
    ports:
      - "8080:8080"
    volumes:
      - ./Service 1/app:/app
    networks:
      - services-network

  db:
    image: postgres:14.5
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mlend2end
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - services-network

volumes:
  pgdata:

networks:
  services-network:



