version: '3.7'
services:
  api:
    image: api-web-service-1:dev
    build: 
      context: "./Service 1"
    container_name: api-web
    ports:
      - "8080:8080"
    volumes:
      - ./Service 1/app:/app
    networks:
      - services-network

networks:
  services-network: